name: "Project orchestration"

on:
  issues:
  pull_request:

jobs:
  copy-to-project:
    runs-on: ubuntu-latest
    steps:
      
      - name: new-item-to-project
        uses: actions/github-script@v5
        env:
          ISSUE_ID: ${{ github.event.issue.node_id }}
        with:
          script: |
            const PROJECT_ID="PN_kwHOACdIos4AAZ_F";
            const ISSUE_ID = process.env.ISSUE_ID;
            const query = `mutation {
              addProjectNextItem(
                input: {
                  projectId: ${PROJECT_ID}
                  contentId: ${ISSUE_ID}
                }
              )
            }`;
            console.log(ISSUE_ID);

