name: "Project orchestration"

on:
  issues:
  pull_request:

jobs:
  copy-to-project:
    runs-on: ubuntu-latest
    steps:
      
      - name: sanity-check
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh api graphql -f query='
            {
              user(login: "gh-projects-cli-bot") {
                projectsUrl
                projectsNext(first: 10) {
                  nodes {
                    id
                    title
                  }
                }
                projectNext(number: 2) {
                  id
                }
              }
            }
            '

      - name: new-item-to-project

        env:
          CONTENT_ID: ${{ github.event.issue.node_id }}
          PROJECT_ID: "PN_kwHOACdIos4AAZ_F"
          GITHUB_TOKEN: ${{ SECRETS.GH_PAT }}
        run: |
          gh api graphql -f query='mutation($projectId:String!, $contentId:String!) {
            addProjectNextItem(
              input: {
                projectId: $projectId
                contentId: $contentId
              }
            ) {
              projectNextItem {
                id
              }
            }
          }' -f projectId=$PROJECT_ID -f contentId=$CONTENT_ID

