name: "Project orchestration"

on:
  issues:
  pull_request:

jobs:
  copy-to-project:
    runs-on: ubuntu-latest
    steps:
      
      - name: sanity-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api graphql -f query='
            {
              user(login: "gh-projects-cli-bot") {
                projectsUrl
                projectsNext(first: 10) {
                  nodes {
                    id
                    title
                  }
                }
                projectNext(number: 2) {
                  id
                }
              }
            }
            '

      - name: new-item-to-project
        uses: actions/github-script@v5
        env:
          contentId: ${{ github.event.issue.node_id }}
          projectId: "PN_kwHOACdIos4AAZ_F"
        with:
          github-token: ${{ SECRETS.GH_PAT }}
          script: |
            const query = `mutation($projectId:String!, $contentId:String!) {
              addProjectNextItem(
                input: {
                  projectId: $projectId
                  contentId: $contentId
                }
              ) {
                projectNextItem {
                  id
                }
              }
            }`;

            const {contentId, projectId} = process.env;
            const result = await github.graphql(query, {contentId, projectId});
            console.log(result);

            
