name: "Project orchestration"

on:
  issues:
  pull_request:

jobs:
  copy-to-project:
    runs-on: ubuntu-latest
    steps:
      
      - name: new-item-to-project
        uses: actions/github-script@v5
        env:
          issueId: ${{ github.event.issue.node_id }}
          projectId: "PN_kwHOACdIos4AAZ_F";
        with:
          script: |
            const query = `mutation($projectId:String!, $contentId:String!) {
              addProjectNextItem(
                input: {
                  projectId: $projectId
                  contentId: $contentId
                }
              )
            }`;

            const {issueId, projectId} = process.env;
            const result = await github.graphql(query, {issueId, projectId});
            console.log(result);

